# Generated by Django 3.2.8 on 2021-10-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('created_date', models.DateField()),
                ('averangeRating', models.FloatField()),
                ('developer', models.CharField(max_length=300)),
            ],
        ),
    ]
