# Generated by Django 3.2.8 on 2021-10-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_awards_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
