# Generated by Django 3.2.8 on 2021-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_award_linktosite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='averangeRating',
            field=models.FloatField(default=0),
        ),
    ]
