# Generated by Django 3.2.8 on 2021-10-24 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_projectreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectReview',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='comment',
        ),
    ]
